W4D2/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests

  
end

W4D2/ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: %w(black grey orange calico white other) }
  validates :sex, inclusion: { in: %w(M F) }

  include ActionView::Helpers::DateHelper

  has_many :rental_requests,
           foreign_key: :cat_id,
           class_name: :CatRentalRequest,
           dependent: :destroy

  def age
    time_ago_in_words(self.birth_date)
  end
end

W4D2/ninety_nine_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validate :does_not_overlap_approved_request

  belongs_to :cat

  def overlapping_requests
    cat.rental_requests.where("(start_date - :end_date) * (:start_date - end_date) >= 0 AND id != :id",
                    {start_date: self.start_date, end_date: self.end_date, id: self.id} )
  end

  def overlapping_approved_requests
    overlapping_requests.select { |request| request.status == "APPROVED" }
  end

  def overlapping_pending_requests
    overlapping_requests.select { |request| request.status == "PENDING" }
  end

  def does_not_overlap_approved_request
    overlapping_approved_requests.empty?
  end

  def approve!
    CatRentalRequest.transaction do
      self.status = "APPROVED"
      self.save
      overlapping_approved_requests.each(&:deny!)
    end
  end

  def deny!
    self.status = "DENIED"
    self.save
  end

  def pending?
    self.status == "PENDING"
  end
end

W4D2/ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

W4D2/ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)

    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat)
    else
      render json: @cat_rental_request.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update

  end

  def index

  end

  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])

    if @cat_rental_request
      redirect_to cat_url(@cat_rental_request.cat)
    else
      render json: @cat_rental_request.errors.full_messages, status: 404
    end

  end

  def destroy

  end

  private

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

W4D2/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    if @cat
      render :show
    else
      render json: @cat.errors.full_messages, status: 404
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])

    if @cat
      render :edit
    else
      render json: @cat.errors.full_messages, status: 404
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end



  private

  def cat_params
    params.require(:cat).permit(:birth_date, :name, :sex, :color, :description)
  end
end

W4D2/ninety_nine_cats/app/views/cats/_form.html.erb
<% if action == :create %>
  <% action_url = cats_url %>
<% else %>
  <% action_url = cat_url(cat) %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :update %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <%= cat.color ? "" : "selected" %>>Please Select Color</option>
    <option value="black" <%= cat.color == "black" ? "selected" : "" %>>Black</option>
    <option value="grey" <%= cat.color == "grey" ? "selected" : "" %>>Grey</option>
    <option value="orange" <%= cat.color == "orange" ? "selected" : "" %>>Orange</option>
    <option value="calico" <%= cat.color == "calico" ? "selected" : "" %>>Calico</option>
    <option value="white" <%= cat.color == "white" ? "selected" : "" %>>White</option>
    <option value="other" <%= cat.color == "other" ? "selected" : "" %>>Other</option>
  </select>
  <br>

  <label for="sex">Sex</label>
  <select id="sex" name="cat[sex]">
    <option disabled <%= cat.sex ? "" : "selected" %>>Please Select Sex</option>
    <option value="M" <%= cat.sex == "M" ? "selected" : "" %>>Male</option>
    <option value="F" <%= cat.sex == "F" ? "selected" : "" %>>Female</option>
  </select>

  <br>

  <label for="birth_date">Birthdate</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>

  <label for="description">Description</label>
  <textarea name="cat[description]">
    <%= cat.description %>
  </textarea>
  <br>

  <%= button_to 'Submit', action_url, method: action %>
</form>

W4D2/ninety_nine_cats/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render 'form', cat: @cat, action: :update %>

W4D2/ninety_nine_cats/app/views/cats/index.html.erb
<h1>ALL THE CATS!</h1>

<% @cats.each do |cat| %>
  <%= cat.name %>
  <%= link_to 'Learn about this cat', cat_url(cat) %>
  <br>
<% end %>

W4D2/ninety_nine_cats/app/views/cats/new.html.erb
<h1>Make a New Cat!</h1>

<%= render 'form', cat: @cat, action: :create %>

W4D2/ninety_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Age</th>
    <th>Description</th>
  </tr>
  <tr>
    <td> <%= @cat.name %> </td>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.sex %> </td>
    <td> <%= @cat.age %> </td>
    <td> <%= @cat.description %> </td>
  </tr>
</table>

<h2>Scheduled Rentals</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
    <th>Update Status</th>
  </tr>
  <% @cat.rental_requests.order(:start_date).each do |request| %>
  <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.status %></td>
    <td><% if request.pending? %>
          <%= button_to 'Approve',  %>
    </td>
  </tr>
  <% end %>
</table>