W5D2/reddit_on_rails/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

W5D2/reddit_on_rails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User,
    inverse_of: :subs

  has_many :post_subs, inverse_of: :sub, dependent: :destroy

  has_many :posts, through: :post_subs, source: :post
end

W5D2/reddit_on_rails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in, except: [:index, :show]
  before_action :require_moderator, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = current_sub
    render :edit
  end

  def update
    @sub = current_sub

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = current_sub
    @posts = @sub.posts
    render :show
  end

  def destroy
    @sub = current_sub
    @sub.destroy
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def current_sub
    Sub.find_by(id: params[:id])
  end

  def require_moderator
    return if current_user.is_moderator?(current_sub)
    redirect_to sub_url(current_sub)
  end
end

W5D2/reddit_on_rails/app/helpers/subs_helper.rb
module SubsHelper
end

W5D2/reddit_on_rails/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render 'shared/errors' %>

<form action=" <%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>

  <input type="text" name="sub[title]" value="<%= @sub.title %>">
  <br>

  <textarea name="sub[description]"><%= @sub.description %>"</textarea>
  <br>

  <input type="submit" value="Edit Sub">
</form>

W5D2/reddit_on_rails/app/views/subs/index.html.erb
<h1>Subs</h1>

<section>
<% @subs.each do |sub| %>
  <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
  <br>
<% end %>
</section>

<section class="buttons">
  <%= button_to "New Sub", new_sub_url, method: :get %>
  <%= button_to "New Post", new_post_url, method: :get %>
</section>

W5D2/reddit_on_rails/app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render 'shared/errors' %>

<form action=" <%= subs_url %>" method="post">
  <%= auth_token %>

  <input type="text" name="sub[title]" placeholder="Title">
  <br>

  <textarea name="sub[description]" placeholder="Description"></textarea>
  <br>

  <input type="submit" value="Create Sub">
</form>

W5D2/reddit_on_rails/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h3><%= @sub.description %></h3>

<section>
  <% @posts.each do |post| %>
    <a href="<%= post_url(post) %>"><%= post.title %></a>
    <br>
  <% end %>
</section>